databases:
  - name: florette-db
    databaseName: florette
    user: florette
    plan: free

services:
  - type: web
    name: florette
    runtime: python
    rootDir: florette
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn florette.wsgi:application
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: florette-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
